"""
Code Explanation Workflow

This workflow handles code explanation requests directly through
the LLM without using the retrieval pipeline.
"""

from src.llm.llm_client import LLMClient
from src.utils.logger import logger


class ExplanationWorkflow:
    """
    Workflow for explaining and analyzing user-provided code.
    """

    def __init__(self) -> None:
        """
        Initialize the explanation workflow.
        """

        self.llm = LLMClient(
            temperature=0.2,
            max_tokens=1500,
        )

        logger.info(
            "Explanation Workflow initialized successfully."
        )

    def _build_prompt(
        self,
        query: str,
        code: str,
    ) -> str:
        """
        Build the explanation prompt.

        Args:
            query:
                User's question.

            code:
                User-provided source code.

        Returns:
            Prompt for the LLM.
        """

        prompt = (
            "You are an expert programming assistant.\n\n"
            
            "The user wants an explanation of the provided code.\n\n"

            "USER QUESTION:\n"
            + query
            + "\n\n"

            "USER CODE:\n\n"
            "```python\n"
            + code
            + "\n```\n\n"

            "Explain the code clearly and accurately.\n\n"

            "Your explanation should include:\n\n"

            "1. What the code does.\n"
            "2. A step-by-step explanation of the logic.\n"
            "3. The important functions, variables, and operations.\n"
            "4. The algorithm or approach used.\n"
            "5. Time complexity when it can be determined.\n"
            "6. Space complexity when it can be determined.\n"
            "7. Any bugs, edge cases, or potential improvements.\n"
            "8. A simple example when useful.\n\n"

            "Do not use external retrieval or retrieved examples.\n"
            "Focus directly on the code provided by the user.\n\n"

            "Return a clear and beginner-friendly explanation."
        )

        return prompt

    def run(
        self,
        query: str,
        code: str,
    ) -> str:
        """
        Run the code explanation workflow.

        Args:
            query:
                User's question about the code.

            code:
                Source code provided by the user.

        Returns:
            Explanation generated by the LLM.
        """

        if not query or not query.strip():
            raise ValueError(
                "Query cannot be empty."
            )

        if not code or not code.strip():
            raise ValueError(
                "Code cannot be empty."
            )

        try:

            logger.info(
                "Starting code explanation workflow."
            )

            # ==========================================
            # Step 1: Build explanation prompt
            # ==========================================

            prompt = self._build_prompt(
                query=query,
                code=code,
            )

            logger.info(
                "Explanation prompt built successfully."
            )

            # ==========================================
            # Step 2: Send prompt directly to LLM
            # ==========================================

            explanation = self.llm.generate(
                prompt
            )

            logger.info(
                "Code explanation generated successfully."
            )

            return explanation

        except Exception:

            logger.exception(
                "Code explanation workflow failed."
            )

            raise